version: "3"

services:

    # Setup for the client
    client:
      build:
        context: ./client
        dockerfile: Dockerfile

      image: client
      container_name: client
      restart: always

      ports:
        - "1234:1234"
      volumes:
        - ./client:/client
        - ./client/node_modules

      networks:
        - app-network



     # Setup for the API
#    api:
#      build:
#        context: .api/
#        dockerfile: Dockerfile
#
#      image: api
#      container_name: api
#      restart: always
#
#      ports:
#        - "9000:9000"
#      volumes:
#        - ./api:/api/
#        - ./api/node_modules
#      networks:
#        - app-network


    # Setup for MongoDB
#    mongodb:
#        image: mongo
#        restart: always
#        container_name: mongodb
#        volumes:
#          - ./data-node:/data/db
#        ports:
#          - 27017:27017
#        command: mongod --noauth --smallfiles
#        networks:
#          - app-network


networks:
  app-network:
    driver: bridge