version: "2"

services:
    client:
        image: webapp-client
        restart: always
        ports:
          - "3000:3000"
        working_dir: /client/src/app
        volumes:
          - ./client:/client
          - /client/node_modules
#        links:
#          - api
        networks:
          - webappnetwork

networks:
  webappnetwork:
    driver: bridge