version: "3"

services:
    client:
      build:
        context: ./client
        dockerfile: Dockerfile

      image: client
      container_name: client
      restart: always

      ports:
        - "1234:1234"
      volumes:
        - ./client:/client
        - ./client/node_modules

      networks:
        - app-network

networks:
  app-network:
    driver: bridge